name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libglib2.0-dev-bin gnome-shell-extensions libxml2-utils gettext

    - name: Build
      run: make

    - name: Install
      run: make install

